set shell := ["bash", "-cu"]

build-all:
    GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build -o bin/windows_dk.exe .
    GOOS=darwin GOARCH=amd64 go build -o bin/mac_dk .
    GOOS=linux GOARCH=amd64 go build -o bin/linux_dk .
